service:
  name: virtual-bookshelf-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2

functions:
  goodreads:
    handler: src/goodreads.handle
    memorySize: 128
    description: Api to Goodreads for VirtualBookshelf app
    environment:
      GOODREADS_CLIENT_KEY: '${file(./env.yml):GOODREADS_CLIENT_KEY}'
      GOODREADS_CLIENT_SECRET: '${file(./env.yml):GOODREADS_CLIENT_SECRET}'
    events:
      - http:
          path: v1/goodreads/request-token
          method: post
      - http:
          path: v1/goodreads/access-token
          method: post
