service:
  name: virtual-bookshelf-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2

functions:
  goodreadsRequestToken:
    handler: src/goodreads/request-token.handle
    memorySize: 128
    description: Api to get request-token for VirtualBookshelf app
    events:
      - http:
          path: virtual-bookshelf/v1/goodreads/request-token
          method: get
